# Generated by Django 4.2 on 2026-05-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('W', 'Water'), ('F', 'Fire'), ('G', 'Grass'), ('E', 'Electric'), ('P', 'Psychic'), ('I', 'Ice'), ('D', 'Dragon'), ('DK', 'Dark'), ('FA', 'Fairy')], max_length=30),
        ),
    ]
