# Generated by Django 4.2 on 2026-05-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='region',
            field=models.CharField(choices=[('K', 'Kanto'), ('J', 'Johto'), ('H', 'Hoenn'), ('S', 'Sinnoh'), ('U', 'Unova'), ('KA', 'Kalos'), ('A', 'Alola'), ('G', 'Galar'), ('P', 'Paldea'), ('NA', 'No Definida')], default='NA', max_length=2),
        ),
    ]
