# Generated by Django 4.2 on 2026-05-10 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
    ]
