# Generated by Django 4.2 on 2026-05-26 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.trainer'),
        ),
    ]
